FROM node:16.10.0-alpine as build

WORKDIR /usr/src/app
COPY yarn.lock ./
COPY package.json ./
RUN yarn cache clean && yarn --update-checksums
COPY . ./

ARG REACT_APP_BASE_URL

ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL

RUN yarn && yarn build

# Stage - Production
FROM nginx:stable-alpine as prod
COPY --from=build /usr/src/app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]