name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  BuildDev:
    name: Build Dev
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'

      - name: Install packages and run unit-tests
        run: |
          yarn
        env:
          CI: true

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
        with:
          name: ${{ github.repository }}/react-github-actions-app
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PASSWORD }}
          dockerfile: Dockerfile.prod
          tags: latest
          buildargs: REACT_APP_BASE_URL

  BuildProd:
    name: Build Prod
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'

      - name: Install packages and run unit-tests
        run: |
          yarn
        env:
          CI: true

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
        with:
          name: ${{ github.repository }}/react-github-actions-app
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PASSWORD }}
          dockerfile: Dockerfile.prod
          tags: latest
          buildargs: REACT_APP_BASE_URL

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [BuildDev]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://159.89.163.208:8080'
    steps:
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GIT_PASSWORD }}
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q --filter ancestor=docker.pkg.github.com/${{ github.repository }}/react-github-actions-app:latest --format="{{.ID}}")
            docker rmi docker.pkg.github.com/${{ github.repository }}/react-github-actions-app -f
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/${{ github.repository }}/react-github-actions-app:latest
            docker run -dit -e REACT_APP_BASE_URL='http://142.93.216.2:4000/api' -p 8080:80 docker.pkg.github.com/${{ github.repository }}/react-github-actions-app:latest

  DeployProd:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [BuildProd]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://159.89.163.208:8080'
    steps:
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GIT_PASSWORD }}
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q --filter ancestor=docker.pkg.github.com/${{ github.repository }}/react-github-actions-app:latest --format="{{.ID}}")
            docker rmi docker.pkg.github.com/${{ github.repository }}/react-github-actions-app -f
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/${{ github.repository }}/react-github-actions-app:latest
            docker run -dit -p 8080:80 docker.pkg.github.com/${{ github.repository }}/react-github-actions-app:latest
